<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SovereignID.Auth.Domain\SovereignID.Auth.Domain.csproj" />
    <ProjectReference Include="..\SovereignID.Auth.Application\SovereignID.Auth.Application.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.SharedKernel.Infrastructure\SovereignID.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Nethereum.Signer" Version="4.26.0" />
    <PackageReference Include="Nethereum.Util" Version="4.26.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
  </ItemGroup>

</Project>
