<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SovereignID.VerifiableCredential.Document</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SovereignID.SharedKernel.Domain\SovereignID.SharedKernel.Domain.csproj" />
  </ItemGroup>

</Project>
