<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\bc-verifier\SovereignID.Verifier.Application\SovereignID.Verifier.Application.csproj" />
    <ProjectReference Include="..\..\..\src\bc-issuer\SovereignID.Issuer.Application\SovereignID.Issuer.Application.csproj" />
    <ProjectReference Include="..\..\..\src\bc-issuer\SovereignID.Issuer.Infrastructure\SovereignID.Issuer.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\shared\SovereignID.SharedKernel.Domain\SovereignID.SharedKernel.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\shared\SovereignID.VcSliceA.Eip712\SovereignID.VcSliceA.Eip712.csproj" />
  </ItemGroup>

</Project>
