<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SovereignID.Verifier.Application.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SovereignID.Verifier.Domain\SovereignID.Verifier.Domain.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.SharedKernel.Application\SovereignID.SharedKernel.Application.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.SharedKernel.Domain\SovereignID.SharedKernel.Domain.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.VerifiableCredential.Document\SovereignID.VerifiableCredential.Document.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.VerifiableCredential.Eip712\SovereignID.VerifiableCredential.Eip712.csproj" />
  </ItemGroup>

</Project>
