<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SovereignID.Verifier.Domain\SovereignID.Verifier.Domain.csproj" />
    <ProjectReference Include="..\SovereignID.Verifier.Application\SovereignID.Verifier.Application.csproj" />
    <ProjectReference Include="..\..\shared\SovereignID.SharedKernel.Infrastructure\SovereignID.SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
